title: "SummerisLive"
email: summerislive@outlook.com
timezone: UTC
url: https://poztxa.github.io
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo40.png'
favicon: 'assets/images/favicon.ico'
author: Summer
paginate: 5
paginate_path: "/page:num/"
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-S07GSKMHZF


autopages:
  enabled: true

  categories:
    layouts:
      - "archive.html"
    title: "Posts in category #:cat"
    permalink: "/category/:cat"
    silent: false
    slugify:
      mode: "default"
      case: true

  collections:
    enabled: false

  tags:
    layouts:
      - "archive.html"
    title: "Posts tagged with #:tag"
    permalink: "/tag/:tag"
    silent: false
    slugify:
      mode: "default"
      case: true

  authors:
    enabled: true
    data: "_data/authors.yml"
    layouts:
      - "author.html"
    title: "Posts by :author"
    permalink: "/author/:author/"
    slugify:
      mode: "default"
      cased: true

version_params:
version_dir: "v1.0"
 # Disable so older versions cannot be searched
allow_search: true  
  
# Authors
authors:
  Summer:
    name: Summer
    display_name: Summer
    avatar: 'assets/images/summer.jpg'
    email: heysummerislive@gmail.com
    web: https://poztxa.github.io
    twitter: https://twitter.com/summerislive
    description: "Digital Creator, Musician, Host, and Gamer"

# Social
social:
  instagram: https://www.instagram.com/summerislive_/
  facebook: https://www.facebook.com/summerislive
  twitter: https://twitter.com/summerislive


# Plugins
plugins: 
- jekyll-paginate
- jekyll-paginate-categories
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
